export const ASSETS = {
  MAIN_LOGO: '/main_logo.png',
  MAIN_LOGO_NO_BG: '/main_logo_without_bg.png',
  MAIN_BG: '/main_bg.png',
  ILLUSTRATION: '/illustration.svg',
  AVATARS: {
    MALE: [
      '/male_avatars/1.png',
      '/male_avatars/2.png',
      '/male_avatars/3.png',
      '/male_avatars/4.png',
      '/male_avatars/5.png',
    ],
    FEMALE: [
      '/female_avatars/1.png',
      '/female_avatars/2.png',
      '/female_avatars/3.png',
      '/female_avatars/4.png',
      '/female_avatars/5.png',
    ],
  },
  CARDS: {
    CLUBS: {
      '2': '/cards/clubs/2_clubs.png',
      '3': '/cards/clubs/3_clubs.png',
      '4': '/cards/clubs/4_clubs.png',
      '5': '/cards/clubs/5_clubs.png',
      '6': '/cards/clubs/6_clubs.png',
      '7': '/cards/clubs/7_clubs.png',
      '8': '/cards/clubs/8_clubs.png',
      '9': '/cards/clubs/9_clubs.png',
      '10': '/cards/clubs/10_clubs.png',
      'J': '/cards/clubs/J_clubs.png',
      'Q': '/cards/clubs/Q_clubs.png',
      'K': '/cards/clubs/K_clubs.png',
      'A': '/cards/clubs/A_clubs.png',
    },
    DIAMONDS: {
      '2': '/cards/diamonds/2_diamonds.png',
      '3': '/cards/diamonds/3_diamonds.png',
      '4': '/cards/diamonds/4_diamonds.png',
      '5': '/cards/diamonds/5_diamonds.png',
      '6': '/cards/diamonds/6_diamonds.png',
      '7': '/cards/diamonds/7_diamonds.png',
      '8': '/cards/diamonds/8_diamonds.png',
      '9': '/cards/diamonds/9_diamonds.png',
      '10': '/cards/diamonds/10_diamonds.png',
      'J': '/cards/diamonds/J_diamonds.png',
      'Q': '/cards/diamonds/Q_diamonds.png',
      'K': '/cards/diamonds/K_diamonds.png',
      'A': '/cards/diamonds/A_diamonds.png',
    },
    HEARTS: {
      '2': '/cards/hearts/2_hearts.png',
      '3': '/cards/hearts/3_hearts.png',
      '4': '/cards/hearts/4_hearts.png',
      '5': '/cards/hearts/5_hearts.png',
      '6': '/cards/hearts/6_hearts.png',
      '7': '/cards/hearts/7_hearts.png',
      '8': '/cards/hearts/8_hearts.png',
      '9': '/cards/hearts/9_hearts.png',
      '10': '/cards/hearts/10_hearts.png',
      'J': '/cards/hearts/J_hearts.png',
      'Q': '/cards/hearts/Q_hearts.png',
      'K': '/cards/hearts/K_hearts.png',
      'A': '/cards/hearts/A_hearts.png',
    },
    SPADES: {
      '2': '/cards/spades/2_spades.png',
      '3': '/cards/spades/3_spades.png',
      '4': '/cards/spades/4_spades.png',
      '5': '/cards/spades/5_spades.png',
      '6': '/cards/spades/6_spades.png',
      '7': '/cards/spades/7_spades.png',
      '8': '/cards/spades/8_spades.png',
      '9': '/cards/spades/9_spades.png',
      '10': '/cards/spades/10_spades.png',
      'J': '/cards/spades/J_spades.png',
      'Q': '/cards/spades/Q_spades.png',
      'K': '/cards/spades/K_spades.png',
      'A': '/cards/spades/A_spades.png',
    },
  },
} as const;

